coreutils: fix build with 64bit time_t on 32bit arches
| ../../coreutils-6.9/lib/mktime.c: In function 'ydhms_diff':
| ../../coreutils-6.9/lib/mktime.c:105:52: error: size of array 'a' is negative
|   105 | #define verify(name, assertion) struct name { char a[(assertion) ? 1 : -1]; }
|       |                                                    ^
| ../../coreutils-6.9/lib/mktime.c:168:3: note: in expansion of macro 'verify'
|   168 |   verify (long_int_year_and_yday_are_wide_enough,
|       |   ^~~~~~

coreutils tries to determine of mktime() from the c-library
works fine, but when cross-compiling, it unconditionally
assumes buggy behaviour, in which case it will use its own
replacement implementation. These basically are tests for
(g)libc implementation bugs that have existed in ancient
times but aren't relevant anymore.

The alternative implementation makes various assumptions which
don't hold true (and doesn't compile anymore). While more recent
versions of coreutils have fixed those assumptions, it's quite
hard to update the code here without potential licensing issues.

Given mktime() works fine in musl and glibc these days, we can
work-around the issues by simply relying on the c-libraries
mktime() implementation, avoiding all problems with coreutils'
alternative implementation.

I've veryfied this by running the tests both on my musl target,
and my glibc (v2.29) host.

This also reduces code-size slightly.

The ac_cv_func_working_mktime variable here corresponds to the
gl_cv_func_working_mktime variable in more recent versions of
coreutils (gnulib), which is being set in oe-core in meta/site.

Signed-off-by: André Draszik <git@andred.net>
Signed-off-by: Ross Burton <ross.burton@intel.com>